from character import find_char_in_list, Rank, Character


def setup() -> list[Character]:
    # ADDING IN ORDER OF RANK
    all_characters = []

    # ALL OTHER-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Wood", Rank.OTHER, (), other=1),
        Character("Lucky Token", Rank.OTHER, ()),
        Character("Kuma TR", Rank.OTHER, ()),
        Character("Save Count", Rank.OTHER, (), other=1),
        Character("Zombie", Rank.OTHER, ()),
        Character("Expansion Pack", Rank.OTHER, ()),
        Character("Gold", Rank.OTHER, (), other=1000),
        Character("Item", Rank.OTHER, (), other=""),
        Character("Pirate Ship", Rank.OTHER, ()),
        Character("Ancient Ship", Rank.OTHER, ()),
        Character("Rayleigh", Rank.OTHER, ()),
    ]

    # WISP CHAR
    all_characters = all_characters + [
        Character("Wisp", Rank.WISP, ())
    ]

    # ALL COMMON-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Luffy", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Zoro", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Nami", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Usopp", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Sanji", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Chopper", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Buggy", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Gunman", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),
        Character("Swordsman", Rank.COMMON, (find_char_in_list(all_characters, "Wisp"),)),

    ]

    # ALL UNCOMMON-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Ace", Rank.UNCOMMON, (find_char_in_list(all_characters, "Luffy"),
                                         find_char_in_list(all_characters, "Gunman"))),
        Character("Robin", Rank.UNCOMMON, (find_char_in_list(all_characters, "Nami"),
                                           find_char_in_list(all_characters, "Sanji"))),
        Character("Brook", Rank.UNCOMMON, (find_char_in_list(all_characters, "Zoro"),
                                           find_char_in_list(all_characters, "Chopper"))),
        Character("Sogeking", Rank.UNCOMMON, find_char_in_list(all_characters, "Usopp") * 2),
        Character("Franky", Rank.UNCOMMON, (find_char_in_list(all_characters, "Usopp"),
                                            find_char_in_list(all_characters, "Luffy"))),
        Character("Fukuro", Rank.UNCOMMON, find_char_in_list(all_characters, "Swordsman") * 2),
        Character("Tashigi", Rank.UNCOMMON, (find_char_in_list(all_characters, "Swordsman"),
                                             find_char_in_list(all_characters, "Gunman"))),
        Character("Blueno", Rank.UNCOMMON, find_char_in_list(all_characters, "Gunman") * 2),
        Character("Hatchan", Rank.UNCOMMON, (find_char_in_list(all_characters, "Gunman"),
                                             find_char_in_list(all_characters, "Nami"))),
        Character("Perona", Rank.UNCOMMON, (find_char_in_list(all_characters, "Buggy"),
                                            find_char_in_list(all_characters, "Nami"))),
        Character("Inazuma", Rank.UNCOMMON, (find_char_in_list(all_characters, "Sanji"),
                                             find_char_in_list(all_characters, "Zoro"))),
        Character("Bepo", Rank.UNCOMMON, (find_char_in_list(all_characters, "Chopper"),
                                          find_char_in_list(all_characters, "Luffy"))),
        Character("Chopper 2", Rank.UNCOMMON, find_char_in_list(all_characters, "Chopper") * 2),

    ]

    # ALL SPECIAL-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Luffy 2", Rank.SPECIAL, find_char_in_list(all_characters, "Luffy") * 3),
        Character("Nami 2", Rank.SPECIAL, find_char_in_list(all_characters, "Nami") * 3),
        Character("Sanji 2", Rank.SPECIAL, find_char_in_list(all_characters, "Sanji") * 3),
        Character("Zoro 2", Rank.SPECIAL, find_char_in_list(all_characters, "Zoro") * 3),
        Character("Buggy 2", Rank.SPECIAL, find_char_in_list(all_characters, "Buggy") * 3),
        Character("Robin 2", Rank.SPECIAL, find_char_in_list(all_characters, "Chopper") +
                  find_char_in_list(all_characters, "Robin") * 2),
        Character("Marco", Rank.SPECIAL, (find_char_in_list(all_characters, "Ace"),
                                          find_char_in_list(all_characters, "Blueno"),
                                          find_char_in_list(all_characters, "Sanji"))),
        Character("Chaka", Rank.SPECIAL, (find_char_in_list(all_characters, "Blueno"),
                                          find_char_in_list(all_characters, "Fukuro"),
                                          find_char_in_list(all_characters, "Chopper"))),
        Character("Lucchi", Rank.SPECIAL, (find_char_in_list(all_characters, "Fukuro"),
                                           find_char_in_list(all_characters, "Robin"),
                                           find_char_in_list(all_characters, "Luffy"))),
        Character("Capone", Rank.SPECIAL, (find_char_in_list(all_characters, "Fukuro"),
                                           find_char_in_list(all_characters, "Gunman"),
                                           find_char_in_list(all_characters, "Buggy"))),
        Character("Law", Rank.SPECIAL, (find_char_in_list(all_characters, "Bepo"),
                                        find_char_in_list(all_characters, "Tashigi"),
                                        find_char_in_list(all_characters, "Buggy"))),
        Character("Kuma", Rank.SPECIAL, (find_char_in_list(all_characters, "Bepo"),
                                         find_char_in_list(all_characters, "Franky"),
                                         find_char_in_list(all_characters, "Zoro"))),
        Character("Drake", Rank.SPECIAL, (find_char_in_list(all_characters, "Tashigi"),
                                          find_char_in_list(all_characters, "Fukuro"),
                                          find_char_in_list(all_characters, "Chopper"))),
        Character("Killer", Rank.SPECIAL, (find_char_in_list(all_characters, "Tashigi"),
                                           find_char_in_list(all_characters, "Brook"),
                                           find_char_in_list(all_characters, "Buggy"))),
        Character("Smoker", Rank.SPECIAL, (find_char_in_list(all_characters, "Gunman")
                                           , find_char_in_list(all_characters, "Tashigi"),
                                           find_char_in_list(all_characters, "Swordsman"))),
        Character("Bon Clay", Rank.SPECIAL, (find_char_in_list(all_characters, "Inazuma"),
                                             find_char_in_list(all_characters, "Robin"),
                                             find_char_in_list(all_characters, "Nami"))),
        Character("Inazuma 2", Rank.SPECIAL, find_char_in_list(all_characters, "Inazuma") * 2),
        Character("Franky 2", Rank.SPECIAL,
                  find_char_in_list(all_characters, "Franky") * 2 + find_char_in_list(all_characters, "Zoro")),
        Character("Crocodile", Rank.SPECIAL, (find_char_in_list(all_characters, "Franky"),
                                              find_char_in_list(all_characters, "Sogeking"),
                                              find_char_in_list(all_characters, "Buggy"))),
        Character("Moria", Rank.SPECIAL,
                  find_char_in_list(all_characters, "Brook") * 2 + find_char_in_list(all_characters, "Sanji")),
        Character("Helmeppo", Rank.SPECIAL, (find_char_in_list(all_characters, "Brook")
                                             , find_char_in_list(all_characters, "Zoro"),
                                             find_char_in_list(all_characters, "Sanji"))),
        Character("Ace 2", Rank.SPECIAL,
                  find_char_in_list(all_characters, "Ace") * 2 + find_char_in_list(all_characters, "Usopp")),
        Character("Jinbe", Rank.SPECIAL, (find_char_in_list(all_characters, "Ace"),
                                          find_char_in_list(all_characters, "Fukuro"),
                                          find_char_in_list(all_characters, "Buggy"))),
        Character("Arlong", Rank.SPECIAL,
                  find_char_in_list(all_characters, "Hatchan") * 2 + find_char_in_list(all_characters, "Luffy")),
        Character("Kuro", Rank.SPECIAL, (find_char_in_list(all_characters, "Hatchan"),
                                         find_char_in_list(all_characters, "Swordsman"),
                                         find_char_in_list(all_characters, "Zoro"))),
        Character("Squard", Rank.SPECIAL, (find_char_in_list(all_characters, "Chopper 2"),
                                           find_char_in_list(all_characters, "Franky"),
                                           find_char_in_list(all_characters, "Nami"))),
        Character("Chopper Guard", Rank.SPECIAL, (find_char_in_list(all_characters, "Chopper 2"),
                                                  find_char_in_list(all_characters, "Inazuma"),
                                                  find_char_in_list(all_characters, "Swordsman"))),
        Character("Chopper Brain", Rank.SPECIAL, (find_char_in_list(all_characters, "Chopper 2"),
                                                  find_char_in_list(all_characters, "Robin"),
                                                  find_char_in_list(all_characters, "Buggy"))),
        Character("Basil", Rank.SPECIAL, (find_char_in_list(all_characters, "Perona"),
                                          find_char_in_list(all_characters, "Blueno"),
                                          find_char_in_list(all_characters, "Usopp"))),
        Character("Kidd", Rank.SPECIAL, (find_char_in_list(all_characters, "Perona"),
                                         find_char_in_list(all_characters, "Bepo"),
                                         find_char_in_list(all_characters, "Buggy"))),
        Character("Enel", Rank.SPECIAL, (find_char_in_list(all_characters, "Sogeking"),
                                         find_char_in_list(all_characters, "Bepo"),
                                         find_char_in_list(all_characters, "Sanji"))),
        Character("Usopp 2", Rank.SPECIAL, find_char_in_list(all_characters, "Sogeking") * 2),
        Character("Absalom", Rank.SPECIAL,
                  find_char_in_list(all_characters, "Zombie") * 3 + find_char_in_list(all_characters, "Nami")),
    ]

    # ALL RARE-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Luffy 3", Rank.RARE, (find_char_in_list(all_characters, "Luffy 2"),
                                         find_char_in_list(all_characters, "Enel"),
                                         find_char_in_list(all_characters, "Bon Clay"))),
        Character("Sanji 3", Rank.RARE, (find_char_in_list(all_characters, "Sanji 2"),
                                         find_char_in_list(all_characters, "Chopper Guard"),
                                         find_char_in_list(all_characters, "Kidd"))),
        Character("Zoro 3", Rank.RARE, (find_char_in_list(all_characters, "Zoro 2"),
                                        find_char_in_list(all_characters, "Moria"),
                                        find_char_in_list(all_characters, "Smoker"))),
        Character("Mihawk", Rank.RARE, (find_char_in_list(all_characters, "Zoro 2"),
                                        find_char_in_list(all_characters, "Kuro"),
                                        find_char_in_list(all_characters, "Drake"))),
        Character("Hancock", Rank.RARE, (find_char_in_list(all_characters, "Nami 2"),
                                         find_char_in_list(all_characters, "Arlong"),
                                         find_char_in_list(all_characters, "Luffy 2"))),
        Character("Crocodile 2", Rank.RARE, (find_char_in_list(all_characters, "Crocodile"),
                                             find_char_in_list(all_characters, "Jinbe"),
                                             find_char_in_list(all_characters, "Bon Clay"))),
        Character("Vivi", Rank.RARE, (find_char_in_list(all_characters, "Chaka"),
                                      find_char_in_list(all_characters, "Crocodile"),
                                      find_char_in_list(all_characters, "Nami 2"))),
        Character("Baby 5", Rank.RARE, (find_char_in_list(all_characters, "Franky 2"),
                                        find_char_in_list(all_characters, "Kuma"),
                                        find_char_in_list(all_characters, "Lucchi"))),
        Character("Sentomaru", Rank.RARE, (find_char_in_list(all_characters, "Kuma"),
                                           find_char_in_list(all_characters, "Chopper Brain"),
                                           find_char_in_list(all_characters, "Capone"))),
        Character("Garp", Rank.RARE, (find_char_in_list(all_characters, "Smoker"),
                                      find_char_in_list(all_characters, "Luffy 2"),
                                      find_char_in_list(all_characters, "Drake"))),
        Character("Magellan", Rank.RARE, (find_char_in_list(all_characters, "Jinbe"),
                                          find_char_in_list(all_characters, "Ace 2"),
                                          find_char_in_list(all_characters, "Buggy 2"))),
        Character("Momonga", Rank.RARE, (find_char_in_list(all_characters, "Jinbe"),
                                         find_char_in_list(all_characters, "Smoker"),
                                         find_char_in_list(all_characters, "Helmeppo"))),
        Character("Blackbeard", Rank.RARE, (find_char_in_list(all_characters, "Ace 2"),
                                            find_char_in_list(all_characters, "Squard"),
                                            find_char_in_list(all_characters, "Drake"))),
        Character("Akainu", Rank.RARE, (find_char_in_list(all_characters, "Ace 2"),
                                        find_char_in_list(all_characters, "Inazuma 2"),
                                        find_char_in_list(all_characters, "Crocodile"))),
        Character("Aokiji", Rank.RARE, (find_char_in_list(all_characters, "Robin 2"),
                                        find_char_in_list(all_characters, "Enel"),
                                        find_char_in_list(all_characters, "Squard"))),
        Character("Kizaru", Rank.RARE, (find_char_in_list(all_characters, "Helmeppo"),
                                        find_char_in_list(all_characters, "Law"),
                                        find_char_in_list(all_characters, "Kidd"))),
        Character("Kaku", Rank.RARE, (find_char_in_list(all_characters, "Lucchi"),
                                      find_char_in_list(all_characters, "Chaka"),
                                      find_char_in_list(all_characters, "Robin 2"))),
        Character("Law 2", Rank.RARE, (find_char_in_list(all_characters, "Law"),
                                       find_char_in_list(all_characters, "Chopper Brain"),
                                       find_char_in_list(all_characters, "Franky 2"))),
        Character("Burgess", Rank.RARE, (find_char_in_list(all_characters, "Basil"),
                                         find_char_in_list(all_characters, "Marco"),
                                         find_char_in_list(all_characters, "Buggy 2"))),
        Character("Basil 2", Rank.RARE, (find_char_in_list(all_characters, "Basil"),
                                         find_char_in_list(all_characters, "Law"),
                                         find_char_in_list(all_characters, "Killer"))),
        Character("Oars", Rank.RARE, (find_char_in_list(all_characters, "Moria"),
                                      find_char_in_list(all_characters, "Moria"),
                                      find_char_in_list(all_characters, "Luffy 2"))),
        Character("Ryuma", Rank.RARE, (find_char_in_list(all_characters, "Moria"),
                                       find_char_in_list(all_characters, "Zoro 2"),
                                       find_char_in_list(all_characters, "Sogeking"),
                                       find_char_in_list(all_characters, "Perona"),
                                       find_char_in_list(all_characters, "Swordsman"))),
        Character("Perona 2", Rank.RARE, (find_char_in_list(all_characters, "Absalom"),
                                          find_char_in_list(all_characters, "Perona"),
                                          find_char_in_list(all_characters, "Chopper Brain"),
                                          find_char_in_list(all_characters, "Sanji 2"))),
        Character("Sugar", Rank.RARE, (find_char_in_list(all_characters, "Chopper Brain"),
                                       find_char_in_list(all_characters, "Zoro 2"),
                                       find_char_in_list(all_characters, "Perona"),
                                       find_char_in_list(all_characters, "Usopp"))),
        Character("Brook 2", Rank.RARE, (find_char_in_list(all_characters, "Brook"),
                                         find_char_in_list(all_characters, "Moria"),
                                         find_char_in_list(all_characters, "Lucchi"))),
        Character("Doflamingo", Rank.RARE, (find_char_in_list(all_characters, "Chopper Guard"),
                                            find_char_in_list(all_characters, "Lucchi"),
                                            find_char_in_list(all_characters, "Buggy 2"))),
        Character("Chopper Horn", Rank.RARE, (find_char_in_list(all_characters, "Chopper Guard"),
                                              find_char_in_list(all_characters, "Helmeppo"),
                                              find_char_in_list(all_characters, "Law"))),
        Character("Shanks", Rank.RARE, (find_char_in_list(all_characters, "Buggy 2"),
                                        find_char_in_list(all_characters, "Usopp 2"),
                                        find_char_in_list(all_characters, "Luffy 2"))),
        Character("Benn", Rank.RARE, (find_char_in_list(all_characters, "Usopp 2"),
                                      find_char_in_list(all_characters, "Smoker"),
                                      find_char_in_list(all_characters, "Enel"))),
        Character("Usopp 3", Rank.RARE, (find_char_in_list(all_characters, "Usopp 2"),
                                         find_char_in_list(all_characters, "Capone"),
                                         find_char_in_list(all_characters, "Nami 2"))),
        Character("Ivankov", Rank.RARE, (find_char_in_list(all_characters, "Inazuma 2"),
                                         find_char_in_list(all_characters, "Robin 2"),
                                         find_char_in_list(all_characters, "Crocodile"))),
        Character("Sabo", Rank.RARE, (find_char_in_list(all_characters, "Inazuma 2"),
                                      find_char_in_list(all_characters, "Kuma"),
                                      find_char_in_list(all_characters, "Marco"))),
        Character("Marco 2", Rank.RARE, (find_char_in_list(all_characters, "Marco"),
                                         find_char_in_list(all_characters, "Chopper Guard"),
                                         find_char_in_list(all_characters, "Chaka"))),
        Character("Jozu", Rank.RARE, (find_char_in_list(all_characters, "Squard"),
                                      find_char_in_list(all_characters, "Capone"),
                                      find_char_in_list(all_characters, "Kuro"))),
        Character("Bartolomeo", Rank.RARE, (find_char_in_list(all_characters, "Kuro"),
                                            find_char_in_list(all_characters, "Arlong"),
                                            find_char_in_list(all_characters, "Franky 2"))),
        Character("Vander Decken", Rank.RARE, (find_char_in_list(all_characters, "Arlong"),
                                               find_char_in_list(all_characters, "Jinbe"),
                                               find_char_in_list(all_characters, "Helmeppo"))),
        Character("Wyper", Rank.RARE, (find_char_in_list(all_characters, "Enel"),
                                       find_char_in_list(all_characters, "Usopp 2"),
                                       find_char_in_list(all_characters, "Sanji 2"))),
        Character("Zeff", Rank.RARE, (find_char_in_list(all_characters, "Bon Clay"),
                                      find_char_in_list(all_characters, "Inazuma 2"),
                                      find_char_in_list(all_characters, "Basil"))),
        Character("Kidd 2", Rank.RARE, (find_char_in_list(all_characters, "Kidd"),
                                        find_char_in_list(all_characters, "Nami 2"),
                                        find_char_in_list(all_characters, "Killer"))),
        Character("Kinemon", Rank.RARE, (find_char_in_list(all_characters, "Killer"),
                                         find_char_in_list(all_characters, "Kuro"),
                                         find_char_in_list(all_characters, "Ace 2"))),
        Character("Shiryu", Rank.RARE, (find_char_in_list(all_characters, "Capone"),
                                        find_char_in_list(all_characters, "Drake"),
                                        find_char_in_list(all_characters, "Sanji 2"))),
        Character("Drake 2", Rank.RARE, (find_char_in_list(all_characters, "Drake"),
                                         find_char_in_list(all_characters, "Basil"),
                                         find_char_in_list(all_characters, "Arlong"))),

    ]

    # ALL LEGEND-RANKING CHARACTERS
    all_characters = all_characters + [
        Character("Moria 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Oars"),
                                              find_char_in_list(all_characters, "Ryuma"),
                                              find_char_in_list(all_characters, "Perona 2"),)),
        Character("Luffy Nightmare", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                      find_char_in_list(all_characters, "Luffy 3"),
                                                      find_char_in_list(all_characters, "Ryuma"),
                                                      find_char_in_list(all_characters, "Absalom"),
                                                      find_char_in_list(all_characters, "Oars"),)),
        Character("Jinbe 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Vander Decken"),
                                              find_char_in_list(all_characters, "Law 2"),
                                              find_char_in_list(all_characters, "Akainu"),)),
        Character("Smoker 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                               find_char_in_list(all_characters, "Garp"),
                                               find_char_in_list(all_characters, "Magellan"),
                                               find_char_in_list(all_characters, "Momonga"),)),
        Character("Dragon", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Ivankov"),
                                             find_char_in_list(all_characters, "Sabo"),
                                             find_char_in_list(all_characters, "Vivi"),)),
        Character("Hancock 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                find_char_in_list(all_characters, "Hancock"),
                                                find_char_in_list(all_characters, "Mihawk"),
                                                find_char_in_list(all_characters, "Sanji 3"),)),
        Character("Shiki", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                            find_char_in_list(all_characters, "Wyper"),
                                            find_char_in_list(all_characters, "Kaku"),
                                            find_char_in_list(all_characters, "Magellan"),)),
        Character("Sengoku", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Akainu"),
                                              find_char_in_list(all_characters, "Aokiji"),
                                              find_char_in_list(all_characters, "Kizaru"),)),
        Character("Shanks 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                               find_char_in_list(all_characters, "Shanks"),
                                               find_char_in_list(all_characters, "Benn"),
                                               find_char_in_list(all_characters, "Sanji 3"),)),
        Character("Whitebeard", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                 find_char_in_list(all_characters, "Jozu"),
                                                 find_char_in_list(all_characters, "Marco 2"),
                                                 find_char_in_list(all_characters, "Kinemon"),)),
        Character("Reiju", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                            find_char_in_list(all_characters, "Magellan"),
                                            find_char_in_list(all_characters, "Crocodile 2"),
                                            find_char_in_list(all_characters, "Baby 5"),)),
        Character("Calgara", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Usopp 3"),
                                              find_char_in_list(all_characters, "Wyper"),
                                              find_char_in_list(all_characters, "Brook 2"),)),
        Character("Laboon", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Brook 2"),
                                             find_char_in_list(all_characters, "Bartolomeo"),
                                             find_char_in_list(all_characters, "Shiryu"),)),
        Character("Bartolomeo 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                   find_char_in_list(all_characters, "Luffy 3"),
                                                   find_char_in_list(all_characters, "Usopp 3"),
                                                   find_char_in_list(all_characters, "Bartolomeo"),)),
        Character("Zoro 4", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Zoro 3"),
                                             find_char_in_list(all_characters, "Perona 2"),
                                             find_char_in_list(all_characters, "Mihawk"),)),
        Character("Lucchi 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                               find_char_in_list(all_characters, "Kaku"),
                                               find_char_in_list(all_characters, "Law 2"),
                                               find_char_in_list(all_characters, "Garp"),)),
        Character("Sanji 4", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Sanji 3")
                                              ,find_char_in_list(all_characters, "Ivankov"),
                                              find_char_in_list(all_characters, "Basil 2"))),
        Character("Koby", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                           find_char_in_list(all_characters, "Shiryu"),
                                           find_char_in_list(all_characters, "Zeff"),
                                           find_char_in_list(all_characters, "Shanks"))),
        Character("Fujitora", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                               find_char_in_list(all_characters, "Kinemon"),
                                               find_char_in_list(all_characters, "Crocodile 2"),
                                               find_char_in_list(all_characters, "Doflamingo"))),
        Character("Sugar 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Sugar"),
                                              find_char_in_list(all_characters, "Basil 2"),
                                              find_char_in_list(all_characters, "Usopp 3"))),
        Character("Luffy 4", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Luffy 3"),
                                              find_char_in_list(all_characters, "Kaku"),
                                              find_char_in_list(all_characters, "Drake 2"))),
        Character("Toki", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*5,
                                           find_char_in_list(all_characters, "Kizaru"),
                                           find_char_in_list(all_characters, "Zoro 3"),
                                           find_char_in_list(all_characters, "Ancient Ship"))),
        Character("Marco 3", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Marco 2"),
                                              find_char_in_list(all_characters, "Hancock"),
                                              find_char_in_list(all_characters, "Baby 5"),)),
        Character("Ulti", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                           find_char_in_list(all_characters, "Chopper Horn"),
                                           find_char_in_list(all_characters, "Benn"),find_char_in_list(all_characters, "Sentomaru"),)),
        Character("Hiluluk", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Chopper Horn"),
                                              find_char_in_list(all_characters, "Burgess"),find_char_in_list(all_characters, "Vander Decken"),)),
        Character("Nekomamushi", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                  find_char_in_list(all_characters, "Kidd 2"),
                                                  find_char_in_list(all_characters, "Wyper"),
                                                  find_char_in_list(all_characters, "Drake 2"),
                                                  )),
        Character("Law 3", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                            find_char_in_list(all_characters, "Law 2"),
                                            find_char_in_list(all_characters, "Kidd 2"),
                                            find_char_in_list(all_characters, "Sentomaru"),)),
        Character("Ace 3", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                            find_char_in_list(all_characters, "Marco 2"),
                                            find_char_in_list(all_characters, "Momonga"),
                                            find_char_in_list(all_characters, "Blackbeard"),)),
        Character("Z", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                        find_char_in_list(all_characters, "Burgess"),
                                        find_char_in_list(all_characters, "Aokiji"),
                                        find_char_in_list(all_characters, "Sabo"),)),
        Character("Caesar", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Doflamingo"),
                                             find_char_in_list(all_characters, "Kizaru"),
                                             find_char_in_list(all_characters, "Garp"),)),
        Character("Nami 3", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Vivi"),
                                             find_char_in_list(all_characters, "Brook 2"),
                                             find_char_in_list(all_characters, "Perona 2"),)),
        Character("Blackbeard 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                                   find_char_in_list(all_characters, "Blackbeard"),
                                                   find_char_in_list(all_characters, "Shiryu"),
                                                   find_char_in_list(all_characters, "Burgess"),)),
        Character("Kuma 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                             find_char_in_list(all_characters, "Sentomaru"),
                                             find_char_in_list(all_characters, "Baby 5"),
                                             find_char_in_list(all_characters, "Chopper Horn"),)),
        Character("Cracker", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Zeff"),
                                              find_char_in_list(all_characters, "Sugar"),
                                              find_char_in_list(all_characters, "Kinemon"),)),
        Character("Shinobu", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                              find_char_in_list(all_characters, "Ryuma"),
                                              find_char_in_list(all_characters, "Blackbeard"),
                                              find_char_in_list(all_characters, "Kinemon"),)),
        Character("King", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*3,
                                           find_char_in_list(all_characters, "Drake 2"),
                                           find_char_in_list(all_characters, "Basil 2"),
                                           find_char_in_list(all_characters, "Doflamingo"),)),
        Character("Rayleigh 2", Rank.LEGENDARY, (find_char_in_list(all_characters, "Wood")*5,
                                                 find_char_in_list(all_characters, "Rayleigh"),
                                                 find_char_in_list(all_characters, "Sentomaru"),
                                                 find_char_in_list(all_characters, "Jinbe"),)),

    ]


    # all_characters = all_characters + [
    #     Character("wisp", Rank.HIDDEN, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.ALTERNATE, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.LIMITED, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.IMMORTAL, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.TRANSCENDED, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.RANDOM, ())
    # ]
    # all_characters = all_characters + [
    #     Character("wisp", Rank.ETERNITY, ())
    # ]
    return all_characters
